# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1024, verbose_name='Label')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='GPUStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashrate', models.PositiveIntegerField()),
                ('temperature', models.PositiveIntegerField()),
                ('fan_speed', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('index', models.PositiveIntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='farms.Farm', verbose_name='Farm')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='farms.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.PositiveIntegerField()),
                ('total_hashrate', models.PositiveIntegerField()),
                ('shares', models.PositiveIntegerField()),
                ('rejected_shares', models.PositiveIntegerField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='farms.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='gpustat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_stats', to='farms.WorkerStat'),
        ),
    ]
