# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpustat',
            name='alt_hashrate',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerstat',
            name='total_alt_hashrate',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
